
// En este fchero types.js definimos los tipos de acciones.

//export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE  = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = ' AUTH_LOGOUT';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';


//export const ADVERTS_CREATED = 'ADVERTS_CREATED';

export const ADVERTS_CREATED_REQUEST = 'ADVERTS_CREATED_REQUEST'
export const ADVERTS_CREATED_SUCCESS = 'ADVERTS_CREATED_SUCCESS'
export const ADVERTS_CREATED_FAILURE = 'ADVERTS_CREATED_FAILURE'

export const UI_RESET_ERROR = 'RESET_ERROR';


export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_REQUEST';
export const TAGS_LOADED_SUCCESS = 'TAGS_LOADED_SUCCESS';
export const TAGS_LOADED_FAILURE = 'TAGS_LOADED_FAILURE';

